version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    working_directory: ~/brazilian-utils
    docker: 
      - image: circleci/openjdk:11.0.2-jdk-browsers
    steps:
      - checkout 
      - restore_cache:
          key: brazilian-utils-{{ checksum "pom.xml" }}      
      - run: mvn dependency:go-offline      
      - save_cache:
          paths:
            - ~/.m2
          key: brazilian-utils-{{ checksum "pom.xml" }}      
      - run: mvn package      
      - store_test_results:
          path: target/surefire-reports      
      - store_artifacts:
          path: target/brazilian-utils.jar